### ISSUE TITLE
Handle empty/root path

### ISSUE THREAD

**Issue by OliverJAsh** [gillchristian/io-ts-reporters#1]
If the type error as at the root, path comes back as empty string, resulting in:

```
Expected type of  to be …
```

**Comment by osdiab** [comment]
Is this actually the case? this test seems to contradict. https://github.com/OliverJAsh/io-ts-reporters/blob/master/tests/index.test.ts#L14

**Comment by osdiab** [comment]
@gillchristian guessing this can be closed
