### ISSUE TITLE
Reporter needs to be parameterized

### ISSUE THREAD

**Issue by justinwoo** [gillchristian/io-ts-reporters#11]
I'm trying to use reporter here: https://github.com/OliverJAsh/io-ts-reporters/blob/d6faa5b95f451974d59981b3f4d188e5b1b119db/src/index.ts#L35

But this doesn't correctly let me use this with any type as I get a mismatch against the empty object. Could you change this to use a parameter <A> instead, or is there something preventing this from working?

**Comment by OliverJAsh** [comment]
Will https://github.com/OliverJAsh/io-ts-reporters/pull/9/files#diff-f41e9d04a45c83f3b6f6e630f10117feR35 help here?

**Comment by justinwoo** [comment]
Does that prevent losing the type information about what the type of the validation result is? I guess it would be fine if so.

**Comment by OliverJAsh** [comment]
I don't think it would prevent that—we would need a generic.
