### ISSUE TITLE
Missing src directory from package - .js.map file pointing at non-existent files

### ISSUE THREAD

**Issue by cravall** [gillchristian/io-ts-reporters#12]
In the published library on NPM, it's missing the top level `src` directory... so the `index.js.map` file is pointing at a non-existent source file.

Not the end of the world but it's giving some warnings here and there during our build pipeline.

**Comment by OliverJAsh** [comment]
Thanks for filing! I'm not sure what the best solution is here. Either publish the `src` directory to npm, or use the TS `inlineSourceMap` + `inlineSources` compiler options. I was reading into what other TS libraries do, such as fp-ts: https://github.com/gcanti/fp-ts/issues/223#issuecomment-422363998. WDYT?

**Comment by cravall** [comment]
@OliverJAsh - I'd probably agree with that comment thread you posted... just don't publish the source files at all, only the definition files.

**Comment by OliverJAsh** [comment]
I see that as non-option because that completely breaks source maps. Source maps are useful for debugging… 🤔

**Comment by osdiab** [comment]
@OliverJAsh what if you built the project with a separate `tsconfig` for distribution, but kept it for local dev  flow? will make a quick PR to demo

**Comment by osdiab** [comment]
is there a problem with publishing src to npm? seems like a pretty small concession

**Comment by gillchristian** [comment]
I'd say it's fine to publish src files
