### ISSUE TITLE
Update io-ts and fp-ts dependencies to 2.x.x

### ISSUE THREAD

**Issue by iippis** [gillchristian/io-ts-reporters#13]
io-ts and fp-ts libraries have released 2.0.x versions. Current versions of the package prevent updating io-ts due to dependency to old io-ts versions.

**Comment by OliverJAsh** [comment]
Hi @iippis, thanks for opening this.

I am no longer using this myself, but I'm happy to hand over the keys if anyone fancies giving this a shot.
