### ISSUE TITLE
UglifyJS build Error

### ISSUE THREAD

**Issue by dderevjanik** [gillchristian/io-ts-reporters#7]
Hi, 
I'm getting this error when trying to build an app:

```
C:\PATH_TO_PROJECT\webpack\build.js:35
                        throw new _gulpUtil2.default.PluginError('webpack', buildError);
                        ^
Error: app-3333a2162c4f3c125228.js from UglifyJs
Unexpected token: operator (>) [C:/PATH_TO_PROJECT/node_modules/io-ts-reporters/target/src/index.js:5,0][app-3333a2162c4f3c125228.js:273839,28]
```

I'm using `node 8.X.Y` , `babel 6.23.0` and building using gulp, which is calling a webpack. In `dev` mode there is no error and working as it supposed to. 

Not sure, what causing this error, but setting `"target": "es5"` in `tsconfig.json` can fix this error.

**Comment by OliverJAsh** [comment]
It looks like UglifyJs is trying to minify this node module, and this node module is distributed as ES6/ES2015.

We can fix this by distributing an ES5 build instead, which will enable UglifyJs to minify it.
